modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/lazynessmind/Snad/issues"
[[mods]]
modId="snad"
version="1.8.7.21a"
displayName="Snad"
credits="TheRoBrit (Original mod)"
authors="lazynessmind (me), TheRoBrit"
description='''You're finally able to have your sugarcane grow faster. What could possibly be better than that?'''
