modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (30 is current forge version)
issueTrackerURL="https://github.com/lazynessmind/Snad/issues" #optional
[[mods]] #mandatory
modId="snad" #mandatory
version="1.8.5.10a" #mandatory
displayName="Snad" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/snad-back-to-the-past" #optional
logoFile="" #optional
credits="TheRoBrit (Original mod)" #optional
authors="lazynessmind (me), TheRoBrit" #optional
description='''You're finally able to have your sugarcane grow faster. What could possibly be better than that?''' #mandatory